export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_FAILURE = "FETCH_COUNTRIES_FAILURE";

export const FETCH_DEPARTMENT = "FETCH_DEPARTMENT";
export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENT_FAILURE = "FETCH_DEPARTMENT_FAILURE";

export const FETCH_POSTINGS = "FETCH_POSTINGS";
export const FETCH_POSTINGS_SUCCESS = "FETCH_POSTINGS_SUCCESS";
export const FETCH_POSTINGS_FAILURE = "FETCH_POSTINGS_FAILURE";

export const FETCH_POSTINGS_COUNTRY = "FETCH_POSTINGS_COUNTRY";
export const FETCH_POSTINGS_COUNTRY_SUCCESS = "FETCH_POSTINGS_COUNTRY_SUCCESS";
export const FETCH_POSTINGS_COUNTRY_FAILURE = "FETCH_POSTINGS_COUNTRY_FAILURE";

export const FETCH_POSTINGS_BY_ID = "FETCH_POSTINGS_BY_ID";
export const FETCH_POSTINGS_BY_ID_SUCCESS = "FETCH_POSTINGS_BY_ID_SUCCESS";
export const FETCH_POSTINGS_BY_ID_FAILURE = "FETCH_POSTINGS_BY_ID_FAILURE";

export const FETCH_POSTINGS_BY_DEPARTMENT = "FETCH_POSTINGS_BY_DEPARTMENT";
export const FETCH_POSTINGS_BY_DEPARTMENT_SUCCESS =
  "FETCH_POSTINGS_BY_DEPARTMENT_SUCCESS";
export const FETCH_POSTINGS_BY_DEPARTMENT_FAILURE =
  "FETCH_POSTINGS_BY_DEPARTMENT_FAILURE";
